net:
    name: AttUNet

dataset:
    name: kits19
    valid_rate: 0.3
    specified_classes:
        - 0
        - 1
        - 1

transform:
    train:
        name: ~

    valid:
        name: ~

training:
    device:
        name: gpu
        ids:
            - 0
    epoch: 100
    batch_size: 2
    eval_epoch_interval: 10
    eval_method: volume
    eval_func: dc
    checkpoint_epoch_interval: 10
    visualize_iter_interval: 0
    balanced_weights: False
    init_weight_func: normal
    num_workers: 0
    log_name: ~

loss:
    name: cross_entropy
    ignore_index: 255

optimizer:
    name: Adam
    lr: 1.0e-4
    weight_decay: 0

scheduler:
    name: reduce_lr_on_plateau
    mode: 'min'
    factor: 0.1
    patience: 5
    verbose: True
    threshold: 0.0001
    threshold_mode: 'rel'
    cooldown: 0
    min_lr: 0
    eps: 1e-08

