net:
    name: DeepLab

dataset:
    name: Cityscapes

transform:
    train:
        name: real_world_transform

    valid:
        name: real_world_transform

training:
    device:
        name: gpu
        ids:
            - 0
    epoch: 1
    batch_size: 5
    eval_epoch_interval: 1
    eval_func: miou
    checkpoint_epoch_interval: 1
    visualize_iter_interval: 20
    balanced_weights: True
    num_workers: 0
    log_name: ~

loss:
    name: cross_entropy
    ignore_index: 255

optimizer:
    name: Adam
    lr: 1.0e-4
    weight_decay: 0

scheduler:
    name: reduce_lr_on_plateau
    mode: 'min'
    factor: 0.1
    patience: 5
    verbose: True
    threshold: 0.0001
    threshold_mode: 'rel'
    cooldown: 0
    min_lr: 0
    eps: 1e-08

